name: Build & Publish Debug APK

on:
  push:
    branches:
      - '**'
  pull_request_target:
    branches:
      - '**'
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        id: upload-apk
        with:
          name: breadboard-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  comment:
    name: Comment on PR
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Download Debug APK'

      - name: Add or Update comment to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            [Download Debug APK](${{ steps.upload-apk.outputs.artifact-url }})
          edit-mode: replace
