name: Build & Publish Debug APK

on:
 push:
    branches:
        - '**'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: jdk
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Configure BugSnag
      run: echo "$(sed -e 's/${bugsnagKey}/${{ secrets.BUGSNAG }}/' app/src/main/AndroidManifest.xml)" > app/src/main/AndroidManifest.xml
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: r34-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
